### ISSUE TITLE
Map type error results in crashes

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-terraform#263] opened 2018-10-08 21:55 UTC
See original issue https://github.com/pulumi/pulumi/issues/2025:

```js
const aws = require("@pulumi/aws");
const lam = new aws.lambda.Function("foo", {
    handler: "",
    role: "",
    runtime: "",
    environment: {
        'TEST_CAPS': 1234,
    }
});
```

`environment` is supposed to have a `variables` key whose value is an object of environment keys and values. Omitting the `variables` key results in a crash like this:

```
    panic: fatal: An assertion has failed: Unexpected duplicate underscore: t_e_s_t__c_a_p_s
    goroutine 90 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc420982000, 0x4a)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x31e6c00, 0x3c20c8e, 0x23, 0xc4206049b0, 0x1, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.TerraformToPulumiName(0xc420bba360, 0x10, 0x0, 0x0, 0x5b16f20, 0x100a371)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/names.go:74 +0x38c
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.getInfoFromTerraformName(0xc420bba360, 0x10, 0xc4206475f0, 0x0, 0xc420bbf900, 0x10, 0xc420604b18, 0x10121f9, 0xc420bbf920)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:754 +0x159
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutputs(0xc420604d68, 0xc4206475f0, 0x0, 0xc4206055e8, 0xc420604e00, 0x98)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:427 +0x105
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutput(0x3507ba0, 0xc420576510, 0xc4202f6000, 0x0, 0xc4206055e8, 0xc420bbf900, 0x0, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:534 +0xa55
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutput(0x3194da0, 0xc42000cb60, 0xc4202f6000, 0x0, 0xc4206055e8, 0xc420bba700, 0xb, 0xc4202f6000)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:503 +0x378
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutputs(0xc4205764e0, 0xc4206475c0, 0xc4205a4cc0, 0xc4206055e8, 0x0, 0xc420bbf8d0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:431 +0x187
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc420542f00, 0x3e35620, 0xc420576390, 0xc4205add40, 0xc420542f00, 0x1, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:360 +0xb1c
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x3e35620, 0xc420576390, 0x3a5c6e0, 0xc4205add40, 0x3e35620, 0xc420576390, 0x3e46880, 0x5b15b50)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1193 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3e35620, 0xc420576390, 0x3a5c6e0, 0xc4205add40, 0xc42000c940, 0xc42000c960, 0x0, 0x0, 0x3e23d00, 0xc4202addb0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x309
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x3b0a960, 0xc420542f00, 0x3e35620, 0xc4205c9ef0, 0xc4200dc0f0, 0xc420138320, 0x0, 0x0, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1195 +0x167
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200de3c0, 0x3e3c780, 0xc42010e000, 0xc4201ac000, 0xc420695f80, 0x5aea810, 0x0, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0x9c8
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200de3c0, 0x3e3c780, 0xc42010e000, 0xc4201ac000, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1318
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4200ce0c0, 0xc4200de3c0, 0x3e3c780, 0xc42010e000, 0xc4201ac000)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/swgillespie/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1
```

If we comment-out the assert, we still get a bad error message:

```
    error: aws:lambda/function:Function resource 'foo' has a problem: environment.0: invalid or unknown key: t_e_s_t__c_a_p_s
```

**Comment by jen20** [comment] 2019-05-13 18:33
Some further details here. From TypeScript, I can't reproduce this - the compiler correctly detects the map value of the wrong type:

```typescript
import * as aws from "@pulumi/aws"

const lam = new aws.lambda.Function("foo", {
    handler: "",
    role: "",
    runtime: "",
    environment: {
        'TEST_CAPS': 1234,
    }
});
```

```
    error: Running program '/Users/James/Code/pulumi-repro/ptf-263' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(8,9): error TS2322: Type '{ 'TEST_CAPS': number; }' is not assignable to type '{ variables?: { [key: string]: Input<string>; } | Promise<{ [key: string]: Input<string>; }> | OutputInstance<{ [key: string]: Input<string>; }> | undefined; } | Promise<{ variables?: { [key: string]: Input<string>; } | Promise<...> | OutputInstance<...> | undefined; }> | OutputInstance<...> | undefined'.
      Object literal may only specify known properties, and ''TEST_CAPS'' does not exist in type 'Input<{ variables?: { [key: string]: Input<string>; } | Promise<{ [key: string]: Input<string>; }> | OutputInstance<{ [key: string]: Input<string>; }> | undefined; }>'.

        at createTSError (/Users/James/Code/pulumi-repro/ptf-263/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/James/Code/pulumi-repro/ptf-263/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/James/Code/pulumi-repro/ptf-263/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/James/Code/pulumi-repro/ptf-263/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (module.js:664:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/James/Code/pulumi-repro/ptf-263/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
```

From JavaScript without type checking, however, it reproduces nicely:

```javascript
const aws = require("@pulumi/aws");

const lam = new aws.lambda.Function("foo", {
    handler: "",
    role: "",
    runtime: "",
    environment: {
        'TEST_CAPS': 1234,
    }
});
```

```
  aws:lambda:Function (foo):
    error: transport is closing

  pulumi:pulumi:Stack (ptf-263-dev):
    panic: fatal: An assertion has failed: Unexpected duplicate underscore: t_e_s_t__c_a_p_s
    goroutine 95 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc0009d0f00, 0x562dd54, 0x23, 0xc000b14c08, 0x1, 0x1)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.TerraformToPulumiName(0xc0009d0f20, 0x10, 0x0, 0x0, 0x97eba40, 0xc000b14c70)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/names.go:74 +0x27d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.getInfoFromTerraformName(0xc0009d0f20, 0x10, 0xc00055b440, 0x0, 0x203000, 0xc000b14d48, 0x100d9d9, 0xc000b1c610, 0xc000b14d60)
```

**Comment by jen20** [comment] 2019-05-13 18:37
I believe implementing #147 would go some way towards fixing this.

**Comment by lukehoban** [comment] 2019-05-13 20:33
Should we close this out as a dupe of #147? Is there anything else we could/should do beyond that?

**Comment by jen20** [comment] 2019-06-01 14:33
Closing as a dupe of #147 which now has some more colour about how we can approach it.

**Closed by jen20** 2019-06-01 14:33 UTC
