### ISSUE TITLE
info: panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#211] opened 2018-07-18 00:36 UTC
A user hit the following failure:

```
    Type                                          Name                                           Plan       Info
 +   pulumi:pulumi:Stack                           container-quickstart-container-quickstart-dev  create..   2 info messages. info:     /home/travis/.gimme/versions/go1.9.linux.am +   pulumi:pulumi:Stack                           container-quickstart-container-quickstart-dev  create..   2 info messages. info:  /home/travis/gopath/src/github.com/pulumi/p +   pulumi:pulumi:Stack                           container-quickstart-container-quickstart-dev  create..   2 info messages. info:  /home/travis/gopath/src/github.com/pulumi/p +   pulumi:pulumi:Stack                           container-quickstart-container-quickstart-dev  create     1 error, 2 info messages
 +   │  ├─ aws:iam:Role                            pulumi-contain-execution                       create
 +   │  ├─ aws:iam:RolePolicyAttachment            pulumi-con-task-32be53a2                       create
 +   │  ├─ aws:iam:RolePolicyAttachment            pulumi-con-task-fd1a00e5                       create
 +   │  └─ aws:iam:RolePolicyAttachment            pulumi-contain-execution                       create
 +   ├─ aws:ecr:Repository                         pulum-164fa748-container                       create
 +   └─ cloud:service:Service                      pulumi-nginx                                   create
 +      ├─ aws:cloudwatch:LogGroup                 pulumi-nginx                                   create
 +      └─ aws:elasticloadbalancingv2:TargetGroup  42dc3ff4                                       create
Diagnostics:
  pulumi:pulumi:Stack: container-quickstart-container-quickstart-dev
    error: transport is closing
  pulumi:pulumi:Stack: container-quickstart-container-quickstart-dev
    info: Building container image 'pulum-164fa748-container': context=./app
    Sending build context to Docker daemon  3.072kB
    Step 1/2 : FROM nginx
     ---> 8b89e48b5f15
    Step 2/2 : COPY index.html /usr/share/nginx/html
     ---> Using cache
     ---> e24f9b4df9ea
    Successfully built e24f9b4df9ea
    Successfully tagged pulum-164fa748-container:latest
  pulumi:pulumi:Stack: container-quickstart-container-quickstart-dev
    info: panic: reflect: call of reflect.Value.Type on zero Value
    goroutine 172 [running]:
    reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:1688 +0x1a3
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validatePrimitive(0xc420501950, 0xc4208db460, 0x9, 0x0, 0x0, 0xc420527590, 0xc4207a14e8, 0x1, 0x1, 0xc4208dd7e0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1531 +0x72
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc420501950, 0xc4208db460, 0x9, 0x0, 0x0, 0xc420527590, 0xc4207a14e8, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1603 +0x5e5
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateList(0xc420501950, 0x3b08015, 0x7, 0x3194200, 0xc4208dd6c0, 0xc4205282d0, 0xc4207a14e8, 0x97, 0x0, 0xc4208db43b, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1339 +0x7f4
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc420501950, 0x3b08015, 0x7, 0x3194200, 0xc4208dd6c0, 0xc4205282d0, 0xc4207a14e8, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1599 +0x9e
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc420501950, 0x3b08015, 0x7, 0xc4205282d0, 0xc4207a14e8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1260 +0x20a
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc420501950, 0x0, 0x0, 0xc420501950, 0xc4207a14e8, 0x3, 0x0, 0x4, 0xc4208dad40, 0x4, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1498 +0x1bf
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc420501950, 0xc4207a14e8, 0xc4208b9d70, 0x3b0385c, 0x4, 0x0, 0x0, 0x100b9c2)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:607 +0x50
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc420217ce0, 0xc4207a14e8, 0x3b056e7, 0x6, 0xc4205373e8, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:270 +0x50
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc420240700, 0x3b056e7, 0x6, 0xc4207a14e8, 0xc42052eea0, 0xc4207a1518, 0x1, 0xc4208b9e00, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0x1d3
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc420531c20, 0x584aa60, 0xc4208b9cb0, 0xc4208dd440, 0xc420531c20, 0x1, 0x1)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:299 +0x845
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x584aa60, 0xc4208b9cb0, 0x385ada0, 0xc4208dd440, 0x584aa60, 0xc4208b9cb0, 0x584fda0, 0x58e85f8)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:734 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x584aa60, 0xc4208b9cb0, 0x385ada0, 0xc4208dd440, 0xc4208dd480, 0xc4208dd4a0, 0x0, 0x0, 0x583ba20, 0xc420247390)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x3a4f1a0, 0xc420531c20, 0x584aa60, 0xc4207fea80, 0xc420858c30, 0xc420468bc0, 0x0, 0x0, 0xc42055ba90, 0x107a271)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:736 +0x16d
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200b0000, 0x584e9a0, 0xc4200ae000, 0xc4202acb00, 0xc4206093b0, 0x58bd2b0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200b0000, 0x584e9a0, 0xc4200ae000, 0xc4202acb00, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420014c20, 0xc4200b0000, 0x584e9a0, 0xc4200ae000, 0xc4202acb00)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1
error: an error occurred while advancing the preview
```

**Comment by lukehoban** [comment] 2018-07-25 23:16
Another user hit this problem as well - it appears to be related to repro when passing the following config:

```
aws:region                                       us-west-2
cloud-aws:ecsClusterARN                          arn:aws:ecs:us-west-2:153052954103:cluster/testcluster
cloud-aws:useFargate                             false
```

With any program using `cloud.Service`, and in particular with:

```typescript
import * as cloud from "@pulumi/cloud-aws";

let rispd = new cloud.Service('dev-rispd', {
    containers: {
        rispddev: {
            image: "redis",
            memory: 16384,
            ports: [{
                port: 8080
            }]
        }
    },
    replicas: 3
});
```

**Comment by pat** [comment] 2018-07-26 14:20
@pgavlin I'll leave this with you to investigate :)

**Comment by pgavlin** [comment] 2018-07-27 02:51
@lukehoban it turns out that this is due to this line: https://github.com/pulumi/pulumi-cloud/blob/master/aws/service.ts#L688

With the config listed above, we have no security group. As a result, we end up creating an array with a single undefined value that gets marshaled as `nil` when it is sent to the engine (and thereby to the resource provider). There is certainly one bug here: the AWS cloud code should not be passing in an undefined value. https://github.com/pulumi/pulumi-cloud/pull/536 has a fix for this.

In addition, it is possible that we should be eliding properties with `nil` values when constructing TF config. I'm going to leave this issue open to track that investigation.

**Comment by lukehoban** [comment] 2018-07-27 03:33
Actually - looking at the code that triggered this again, I see why this is not quite the same case, we end up with an array with a single `undefined` in it, which really shouldn’t be treated the same as an empty array. So I think it’s reasonable that this not work - but of course we should not assert.

**Comment by jen20** [comment] 2018-08-08 01:17
This is a straightforward reproduction of this issue showing the circumstance in which I ran into it. Thanks to @pgavlin for pointing me at this issue:

```
import * as aws from "@pulumi/aws"
import { Output } from "@pulumi/pulumi";

class SomeBuggyClass {
    public iAmUndefined: Output<string>;
}

async function main() {
    const defaultVpc = await aws.ec2.getVpc({
        default: true,
    });

    const defaultSg = new aws.ec2.DefaultSecurityGroup(`vpc-default-sg`, {
        vpcId: defaultVpc.id,
    });

    const firstSubnet = (await aws.ec2.getSubnetIds({
        vpcId: defaultVpc.id,
    })).ids[0];

    const imageId = (await aws.getAmi({
        filters: [
            {name: "name", values: ["amzn2-ami-hvm*"]},
        ],
        owners: ["amazon"],
        mostRecent: true,
    })).id;

    const securityGroupIds = [defaultSg.id, new SomeBuggyClass().iAmUndefined];

    new aws.ec2.Instance(`crasher`, {
        subnetId: firstSubnet,
        vpcSecurityGroupIds: securityGroupIds,

        ami: imageId,
        instanceType: aws.ec2.T2InstanceMicro,
    });
}

const _ = main();
```

Output:

```
❯ pulumi update
Previewing update of stack 'pulumi-crash-repro-2-dev'
Previewing changes:

     Type                             Name                                           Plan       Info
 +   pulumi:pulumi:Stack              pulumi-crash-repro-2-pulumi-crash-repro-2-dev  create     1 error, 1 info message
 +   └─ aws:ec2:DefaultSecurityGroup  vpc-default-sg                                 create

Diagnostics:
  pulumi:pulumi:Stack: pulumi-crash-repro-2-pulumi-crash-repro-2-dev
    info: panic: reflect: call of reflect.Value.Type on zero Value
    goroutine 162 [running]:
    reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
    	/home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:1688 +0x1a3
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validatePrimitive(0xc4201d72f0, 0xc420915ca0, 0x18, 0x0, 0x0, 0xc4200403c0, 0xc420b1b4e8, 0x1, 0x1, 0xc4208846c0, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1531 +0x72
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc4201d72f0, 0xc420915ca0, 0x18, 0x0, 0x0, 0xc4200403c0, 0xc420b1b4e8, 0x0, 0x0, 0x0, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1603 +0x5e5
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateList(0xc4201d72f0, 0x3b6bbce, 0x16, 0x31c6300, 0xc420884620, 0xc420042780, 0xc420b1b4e8, 0x97, 0x0, 0xc42085a782, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1339 +0x7f4
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc4201d72f0, 0x3b6bbce, 0x16, 0x31c6300, 0xc420884620, 0xc420042780, 0xc420b1b4e8, 0x0, 0x0, 0x0, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1599 +0x9e
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc4201d72f0, 0x3b6bbce, 0x16, 0xc420042780, 0xc420b1b4e8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1260 +0x20a
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc4201d72f0, 0x0, 0x0, 0xc4201d72f0, 0xc420b1b4e8, 0x3, 0x0, 0x4, 0xc42077f108, 0x13, ...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1498 +0x1bf
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc4201d72f0, 0xc420b1b4e8, 0xc420b9fef0, 0x0, 0x0, 0xc42007edb0, 0xe, 0x100b9c2)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:607 +0x50
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc420153880, 0xc420b1b4e8, 0x3b49615, 0xc, 0xc420501028, 0x1, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:270 +0x50
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc4202cb260, 0x3b49615, 0xc, 0xc420b1b4e8, 0xc4204fac60, 0xc420b1b518, 0x1, 0xc420b9ff20, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0x1d3
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc4204fdc20, 0x58bdb60, 0xc420b9fe30, 0xc420ba2e80, 0xc4204fdc20, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:300 +0x845
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x58bdb60, 0xc420b9fe30, 0x39f7460, 0xc420ba2e80, 0x58bdb60, 0xc420b9fe30, 0x58c2ea0, 0x595c038)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1185 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x58bdb60, 0xc420b9fe30, 0x39f7460, 0xc420ba2e80, 0xc420884420, 0xc420884440, 0x0, 0x0, 0x58aea20, 0xc42025d360)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x3aa19e0, 0xc4204fdc20, 0x58bdb60, 0xc420dadbf0, 0xc420889540, 0xc420524bc0, 0x0, 0x0, 0xc4205c8a90, 0x107a271)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1187 +0x16d
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200b8000, 0x58c1aa0, 0xc4200b6000, 0xc420770800, 0xc4205f2b40, 0x5930890, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200b8000, 0x58c1aa0, 0xc4200b6000, 0xc420770800, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202b8100, 0xc4200b8000, 0x58c1aa0, 0xc4200b6000, 0xc420770800)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1

  pulumi:pulumi:Stack: pulumi-crash-repro-2-pulumi-crash-repro-2-dev
    error: transport is closing

error: an error occurred while advancing the preview
```

**Closed** 2018-09-06 00:18 UTC
