### ISSUE TITLE
Tag name is converted to lowercase

### ISSUE THREAD

**Issue by gabrielke** [pulumi/pulumi-terraform#430] opened 2019-07-24 07:19 UTC
Tag "Name" is the default displayed on AWS Web Console. I want to have this filled out with reasonable values. 

Please see this snippet:

`s2 = ec2.Instance('mytestlinux',
    tags=[{'Name': 'MyTestLinux'}],
    instance_type=size,
    security_groups=[group.name],
    key_name=key,
    ami=ami)`

Expected result:
Tag "Name" is created and value "MyTestLinux" is displayed on AWS Web console.

Actual result:
Tag "name" is created and value "MyTestLinux" is displayed on AWS Web console.

Conclusion: Tag's name is converted to lowercase (which I guess shouldn't happen).

**Comment by joeduffy** [comment] 2019-08-21 15:00
I'm surprised this code works. I believe the property `tags` is expected to be a dictionary and not an array. (See https://github.com/pulumi/pulumi-aws/blob/a011e2dbc969b65f02c7cda2531b528444fe34e9/sdk/python/pulumi_aws/ec2/instance.py#L238.) Using a dictionary instead, I see the expected behavior (i.e., the tag is `Name`):

`s2 = ec2.Instance('mytestlinux', tags={'Name': 'MyTestLinux'}, instance_type=size, security_groups=[group.name], key_name=key, ami=ami)`

@stack72 @pgavlin Does this check out to you too? What is the expected behavior here? I'd have thought the bridge would fail due to the type mismatch at the very least. I guess the code generated isn't checking object types eagerly either?

**Comment by lukehoban** [comment] 2019-08-21 15:10
> I guess the code generated isn’t checking object types eagerly either?

Yes - we currently don’t check types at runtime in the SDK layer (for either JS or Python). Considering this is tracked in https://github.com/pulumi/pulumi-terraform/issues/147. 

That said - the described symptom of this actually “working” but lowercasing the name is especially odd - and doesn’t seem quite consistent with this lack of type checking being the only problem.

**Comment by joeduffy** [comment] 2019-08-21 15:19
Yup, certainly surprising.

Would have been good to communicate this as a workaround though -- pretty easy fix!

My recollection is that the bridge uses the expected types to drive the casing logic. I suspect our time is better spent fix this to error out sooner on unexpected types, instead of expecting and rewriting all of that downstream code to deal with random types thrown at it, but it's up to you.

**Comment by lukehoban** [comment] 2019-08-22 14:49
Based on the above notes, this looks like it's ultimately a dupe of #147.  I'll close this one out and we'll look into what we can do to catch this class of issues generally earlier.

**Closed by lukehoban** 2019-08-22 14:49 UTC
Labels: feature/q3, kind/bug, language/python
